apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: klinik-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: klinik
  policy:
    semver:
      range: ">=1.0.0"
