apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: klinik-automation
  namespace: learning-image
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: update-image-tags
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
    push:
      branch: main
    secretRef:
      name: github-credentials   # <--- tambahkan ini
  update:
    path: "./"
    strategy: Setters
