apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: klinik-automation
  namespace: learning-image
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: update-image-tags
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: fluxcdbot
        email: fluxcdbot@users.noreply.github.com
      messageTemplate: "update image to {{range .Updated.Images}}{{.NewTag}}{{end}}"
    push:
      branch: main
  update:
    path: ./
    strategy: Setters
